# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pk_1cmt_iv_mm <- function(A, times, doses, len, par, step_size) {
    .Call('PKPDmap_pk_1cmt_iv_mm', PACKAGE = 'PKPDmap', A, times, doses, len, par, step_size)
}

pk_1cmt_iv <- function(A, times, doses, len, par, step_size) {
    .Call('PKPDmap_pk_1cmt_iv', PACKAGE = 'PKPDmap', A, times, doses, len, par, step_size)
}

pk_1cmt_oral <- function(A, times, doses, len, par, step_size) {
    .Call('PKPDmap_pk_1cmt_oral', PACKAGE = 'PKPDmap', A, times, doses, len, par, step_size)
}

